# -*- coding: utf-8 -*-
"""prak 7 algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLWA0ttopmLuegRvzOfLqvuBeepYvamW
"""

def cekbilangan(bil):
    if bil == 1:
        print(f"bilangan {bil} adalah bilangan prima")

    elif bil == 2:
        print(f"bilangan {bil} adalah bilangan prima")

    else:

        global x

        for x in range(2, bil):

            if bil % x == 0:

                stat = 0

                break

            else:
                stat = 1
        cekstat(stat)

def cekstat(stat):

    if stat == 0:
        print(f"bilangan {bil} adalah bukan bilangan prima")
        print(f"{x} kali {bil//x} = {bil}")

    else:
        print(f"{bil} adalah bilangan prima")

a = 1

while a == 1:

    bil = int(input("masukan angkanya : "))
    cekbilangan(bil)
    break


bil = int(input("masukan angkanya : "))
cekbilangan(bil)

jawab = -1

while (jawab == -1):
    try:
        hasil_str = input("masukan angka nya: ")
        hasil = int(hasil_str)  # Coba konversi ke integer
    except ValueError:
        if hasil_str.lower() == 'stop':  # Periksa apakah input adalah "stop"
            print("Program dihentikan.")
            break  # Keluar dari loop jika "stop" dimasukkan
        else:
            print("Input tidak valid. Masukkan angka atau 'stop'.")
            continue  # Lanjut ke iterasi loop berikutnya


    def cekangka(hasil):

      if hasil == 1  or hasil == 11 or hasil == 31 or hasil == 41  :
        print(hasil,"ST")

      elif hasil == 2 or hasil == 22 or hasil == 32 or hasil == 42 :
        print(hasil,"ND")

      elif hasil == 3 or hasil == 13 or hasil == 23 or hasil == 43 :
        print(hasil,"RD")

      elif (hasil <= 50):
        print(hasil,"TH")

      else:
        print("tolong masukan angka yang pasti")


    cekangka(hasil)